# src/main/resources/application.properties
spring.application.name=digital-banking-system-backend

# Server
server.port=8085
spring.datasource.url=jdbc:h2:mem:exam-db
 spring.h2.console.enabled=true
 spring.datasource.driver-class-name=org.h2.Driver